/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import useAnimStore from "@/useAnimStore";
import { useExplode } from "../../../../hooks/useExplode";

export function Brain(props) {
  const { nodes, materials } = useGLTF("/models/brain.glb");

  const menu = useAnimStore((state) => state.menu);

  const groupRef = useRef();

  useExplode(groupRef, {
    distance: 100,
    menu: menu,
  });
  return (
    <group {...props} dispose={null} ref={groupRef}>
      <group rotation={[0, -1.55, 0]} scale={0.02}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["3Dmari_1_fracturepart"].geometry}
          material={materials["Mat.1"]}
          position={[-47.809, -15.846, 23.041]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group
          position={[1.715, 6.827, 57.076]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart1_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart1_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-16.403, 7.606, -13.049]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart10_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart10_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-33.51, -12.559, 46.9]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart11_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart11_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-29.765, 34.455, -35.134]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart12_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart12_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-43.566, 29.334, -13.761]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart12_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart12_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[8.689, 67.137, -7.878]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart13_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart13_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[9.937, 56.544, -5.072]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart13_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart13_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-3.559, 67.452, -7.81]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart13_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart13_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-14.622, 66.463, -7.043]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart13_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart13_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[3.657, 16.991, 72.652]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[4.357, 31.904, 65.669]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[4.694, 40.706, 60.418]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[1.981, 5.053, 74.413]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-11.441, 24.313, 73.527]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_5_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_5_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-7.524, 5.783, 76.631]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_6_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart14_6_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-52.195, 15.54, 2.391]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart15_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart15_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-60.465, 5.348, 6.342]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart15_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart15_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-51.883, 22.732, 0.574]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart15_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart15_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[22.087, 63.799, 29.902]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart16_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart16_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[33.919, 66.572, 6.494]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart16_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart16_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[11.614, 39.523, 75.546]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart17_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart17_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-5.442, 39.863, 80.539]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart17_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart17_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[0.227, 49.098, 69.861]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart17_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart17_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[39.35, 11.396, 13.451]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart18_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart18_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-27.131, 31.02, -7.044]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart19_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart19_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-20.486, 12.145, 53.593]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart1_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart1_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-24.575, 51.64, 39.944]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[5.432, 53.914, 60.831]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart20_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart20_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-12.703, 47.54, 63.721]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart20_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart20_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[14.388, 22.89, 50.333]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart21_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart21_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-1.521, 27.124, 47.646]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart21_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart21_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-35.178, 26.895, 48.292]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart22_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart22_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[26.555, -10.605, 16.621]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart23_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart23_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[25.657, 0.242, 18.033]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart23_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart23_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[30.697, -3.044, 11.415]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart23_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart23_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-43.817, -7.715, 64.033]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart24_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart24_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-49.277, 10.831, 23.294]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart25_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart25_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-38.956, 13.067, 9.516]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart25_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart25_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-39.917, 18.951, 15.689]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart25_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart25_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-46.658, 22.106, 30.611]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart25_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart25_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-44.482, 21.759, 18.697]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart25_5_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart25_5_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-47.311, 8.877, 56.837]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart26_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart26_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["3Dmari_1_fracturepart27"].geometry}
          material={materials["Mat.1"]}
          position={[20.313, 22.672, 6.557]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group
          position={[11.188, 32.698, 0.167]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart28_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart28_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[0.319, 32.967, -1.125]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart28_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart28_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[6.572, -6.391, 85.831]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart29_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart29_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-13.271, -0.788, 85.664]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart29_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart29_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-35.851, 10.837, 27.054]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-17.747, 24.565, 2.7]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart30_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart30_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-38.487, 50.113, 51.771]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart31_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart31_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-47.625, 37.36, 56.703]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart31_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart31_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-48.444, 29.11, 70.697]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart31_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart31_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-37.036, 51.52, 45.75]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart31_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart31_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[49.242, 5.655, 36.424]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart32_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart32_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[47.347, -10.597, 22.229]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart33_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart33_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-46.514, 42.8, 33.74]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart34_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart34_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-42.41, 31.128, 9.772]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart35_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart35_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-45.562, 19.132, -11.015]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart35_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart35_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-46.167, 18.06, 2.025]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart35_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart35_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[7.985, 46.527, -12.641]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart36_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart36_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[9.103, 54.676, -16.923]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart36_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart36_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-4.581, 50.164, -9.773]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart36_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart36_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[29.933, -5.274, 76.813]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart37_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart37_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-32.008, 50.972, 9.247]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart38_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart38_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[17.564, -0.832, 90.459]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart39_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart39_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[20.025, 16.831, 87.235]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart39_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart39_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[33.461, 11.396, 83.998]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart39_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart39_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[38.251, 20.676, 79.721]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart39_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart39_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["3Dmari_1_fracturepart3_2"].geometry}
          material={materials["Mat.1"]}
          position={[-33.653, -1.297, 22.248]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group
          position={[17.132, 42.714, 40.477]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[42.402, -14.023, 59.487]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart40_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart40_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-24.735, -3.894, 14.769]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart41_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart41_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["3Dmari_1_fracturepart41_2"].geometry}
          material={materials["Mat.1"]}
          position={[-26.087, 23.257, 23.711]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group
          position={[24.405, 11.812, -16.946]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart42_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart42_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[28.971, -0.197, -19.56]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart42_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart42_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[14.419, 37.938, 15.069]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart43_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart43_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-1.058, 38.457, 12.133]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart43_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart43_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[40.816, -20.198, 43.332]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart44_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart44_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[18.031, -17.513, 46.273]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart44_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart44_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[24.253, -4.9, -9.967]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart45_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart45_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[22.481, 7.041, -8.189]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart45_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart45_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[24.308, 12.826, -1.036]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart46_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart46_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[17.287, -0.72, 0.235]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart46_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart46_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-38.354, -22.717, 65.023]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart47_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart47_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-57.647, -11.654, 48.914]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart47_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart47_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[11.708, 22.114, -26.566]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart48_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart48_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-3.368, 21.864, -28.862]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart48_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart48_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-13.701, 59.114, -20.646]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart49_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart49_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[0.321, 33.953, 41.207]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart4_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart4_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[1.146, 31.52, 27.67]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart4_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart4_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[13.148, 41.751, -40.942]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart5_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart5_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[43.417, 33.927, 47.263]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart50_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart50_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-44.655, -2.573, -4.151]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart51_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart51_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-64.354, -7.001, 12.244]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart51_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart51_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[19.097, 64.588, -9.051]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart52_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart52_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[32.231, 65.69, 1.16]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart52_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart52_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[6.972, 71.602, 16.249]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart53_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart53_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[9.137, 75.524, 5.368]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart53_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart53_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-10.354, 66.6, 12.159]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart53_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart53_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-22.958, 66.557, -1.029]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart53_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart53_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-44.4, -20.703, 49.42]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart54_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart54_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[52.207, 4.732, 56.425]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart55_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart55_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[58.619, 23.113, 56.005]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart55_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart55_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[22.032, 60.38, -25.858]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart56_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart56_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[15.872, 49.843, -23.499]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart56_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart56_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[38.957, 26.598, 29.06]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart57_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart57_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[3.078, -1.33, 64.82]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart58_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart58_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[4.487, -5.885, 56.866]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart58_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart58_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[4.348, 2.349, 54.99]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart58_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart58_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-16.871, -8.591, 57.255]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart58_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart58_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[0.435, 5.72, 61.106]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart59_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart59_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-1.077, 1.727, 70.828]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart59_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart59_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-21.694, 7.769, 69.258]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart59_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart59_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-4.912, 43.179, -41.968]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart5_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart5_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-54.771, 27.664, 25.212]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart6_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart6_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-21.624, 45.686, -27.506]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart60_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart60_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[20.341, 37.197, -8.256]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart61_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart61_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[8.548, 4.893, 17.765]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart62_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart62_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[12.259, -5.018, 29.898]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart62_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart62_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-6.033, 5.834, 14.223]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart62_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart62_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[46.115, -6.327, 7.973]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart63_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart63_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[63.698, 0.231, 18.117]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart64_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart64_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[58.033, 26.224, 22.876]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart64_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart64_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[59.866, 10.29, 19.776]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart64_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart64_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[62.128, 21.029, 38.82]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart64_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart64_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[13.132, 58.844, -38.492]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart65_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart65_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-4.169, 61.04, -37.428]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart65_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart65_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-0.284, 67.984, -24.431]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart65_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart65_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[7.108, 6.142, 3.793]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart66_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart66_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[14.864, -2.17, 0.945]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart66_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart66_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-5.351, 12.852, 5.121]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart66_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart66_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[32.61, -23.03, 70.594]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart67_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart67_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[7.608, 57.27, 40.383]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart68_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart68_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-4.892, 48.508, 36.515]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart68_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart68_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[49.998, 35.113, 6.888]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart69_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart69_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[43.484, 51.022, 6.791]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart69_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart69_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-59.263, 15.533, 28.479]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart6_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart6_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-62.788, 6.248, 21.598]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart6_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart6_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[-63.7, 5.403, 35.31]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart6_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart6_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-13.79, 56.506, 26.791]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart7_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart7_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["3Dmari_1_fracturepart70"].geometry}
          material={materials["Mat.1"]}
          position={[-15.113, 40.333, -5.338]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <group
          position={[-50.704, -7.143, 27.991]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart71_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart71_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-60.902, 6.597, 41.906]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart71_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart71_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[30.904, 41.494, 65.891]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart72_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart72_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[45.232, 24.713, 70.25]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart72_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart72_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[32.83, 57.352, 52.829]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart72_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart72_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[47.442, 41.187, 57.677]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart72_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart72_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[35.964, 40.286, -31.951]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart73_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart73_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[21.791, 7.922, 32.63]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart74_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart74_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-21.277, 11.49, 23.097]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart75_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart75_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[40.368, 27.769, -7.982]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart76_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart76_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[47.04, 15.843, -14.151]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart76_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart76_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[15.8, 59.804, 10.04]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart77_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart77_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[1.03, 56.634, 7.406]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart77_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart77_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-0.352, 49.558, 9.21]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart77_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart77_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[0.993, 56.061, 15.941]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart77_4_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart77_4_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[3.504, 19.661, 31.279]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart78_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart78_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-11.901, 20.386, 32.21]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart78_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart78_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[19.591, 13.245, 71.525]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart79_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart79_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[14.615, -7.298, 66.275]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart79_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart79_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[31.744, 50.519, -8.604]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart8_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart8_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[39.468, 0.15, -24.044]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart80_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart80_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[36.121, 20.151, -28.919]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart80_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart80_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[29.996, 0.875, 53.817]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart81_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart81_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[14.751, -7.394, 66.121]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart81_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart81_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[51.363, -2.223, -5.869]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart82_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart82_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[54.483, 16.224, -3.322]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart82_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart82_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[35.952, -15.356, -7.138]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart82_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart82_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[9.973, 15.229, 10.529]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart83_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart83_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-0.903, 23.43, 9.368]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart83_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart83_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[11.203, -21.29, 70.593]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart84_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart84_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-10.837, -25.585, 69.387]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart84_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart84_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-2.39, -21.955, 80.184]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart84_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart84_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group position={[33.06, 1.54, -2.69]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart85_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart85_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-35.115, 49.911, -12.638]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart86_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart86_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[38.446, 50.31, 25.086]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart87_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart87_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[56.461, 46.562, 36.355]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart87_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart87_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-34.952, 5.475, 78.647]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart88_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart88_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[27.932, -12.596, -18.329]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart89_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart89_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[0.955, -13.782, 80.458]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart9_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart9_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-26.016, 19.004, -27.062]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart90_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart90_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-37.437, 1.892, -22.669]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart90_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart90_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-40.002, 26.194, -18.041]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart90_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart90_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-30.839, 39.119, 67.737]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart91_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart91_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-40.968, 33.945, 66.083]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart91_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart91_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[6.676, -23.189, 90.633]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart9_2_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart9_2_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
        <group
          position={[-18.763, -18.78, 78.685]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart9_3_1"].geometry}
            material={materials.Mat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["3Dmari_1_fracturepart9_3_2"].geometry}
            material={materials["Mat.1"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/brain.glb");
