/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/coin.glb -o src/app/components/canvas/models/Coin.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import useAnimStore from "@/useAnimStore";
import { useExplode } from "../../../../hooks/useExplode";

export function Coin(props) {
  const { nodes, materials } = useGLTF('/models/coin.glb')

  const menu = useAnimStore((state) => state.menu);

  const groupRef = useRef();

  useExplode(groupRef, {
    distance: 10,
    menu: menu,
    Ix: -1.7,
    Iy:-0.5,
    Iz: -0.5,
    Fx: 1.3,
    Fy: 0,
    Fz: -0.1,
  });
  return (
    <group {...props} dispose={null} ref={groupRef}>
      {/* <group position={[-0.004, -0.014, 0.007]} scale={1.438}>
        <mesh geometry={nodes.Coin.geometry} material={materials.Atlas_Diffuse} position={[0, 0, 0.027]} scale={100} />
      </group> */}
      <mesh geometry={nodes.Coin_cell002.geometry} material={materials.Atlas_Diffuse} position={[-0.343, 0.149, -0.29]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell003.geometry} material={materials.Atlas_Diffuse} position={[0.217, -0.456, 0.606]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell004.geometry} material={materials.Atlas_Diffuse} position={[-0.004, -1.579, -0.39]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell005.geometry} material={materials.Atlas_Diffuse} position={[-1.031, -1.008, -0.248]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell006.geometry} material={materials.Atlas_Diffuse} position={[-0.194, 0.153, -0.163]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell007.geometry} material={materials.Atlas_Diffuse} position={[-0.187, 0.076, -0.091]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell008.geometry} material={materials.Atlas_Diffuse} position={[-0.063, 0.078, -0.081]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell010.geometry} material={materials.Atlas_Diffuse} position={[0.134, 0.139, 0.159]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell011.geometry} material={materials.Atlas_Diffuse} position={[-0.286, -0.72, 0.509]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell012.geometry} material={materials.Atlas_Diffuse} position={[0.599, -0.169, 0.477]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell013.geometry} material={materials.Atlas_Diffuse} position={[0.674, 0.063, 0.502]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell014.geometry} material={materials.Atlas_Diffuse} position={[0.403, -0.101, 0.511]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell015.geometry} material={materials.Atlas_Diffuse} position={[-0.092, 0.685, -0.492]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell016.geometry} material={materials.Atlas_Diffuse} position={[-0.024, 0.51, -0.479]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell018.geometry} material={materials.Atlas_Diffuse} position={[0.189, 0.474, -0.244]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell019.geometry} material={materials.Atlas_Diffuse} position={[0.185, 0.658, -0.525]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell020.geometry} material={materials.Atlas_Diffuse} position={[0.408, 0.648, -0.381]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell021.geometry} material={materials.Atlas_Diffuse} position={[0.769, 0.273, 0.356]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell022.geometry} material={materials.Atlas_Diffuse} position={[-1.003, 0.898, -0.254]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell023.geometry} material={materials.Atlas_Diffuse} position={[0.389, 0.75, -0.267]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell024.geometry} material={materials.Atlas_Diffuse} position={[0.736, -0.238, 0.585]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell025.geometry} material={materials.Atlas_Diffuse} position={[-0.061, 0.614, -0.654]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell026.geometry} material={materials.Atlas_Diffuse} position={[-0.008, -0.287, 0.289]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell027.geometry} material={materials.Atlas_Diffuse} position={[-0.15, -0.516, 0.407]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell029.geometry} material={materials.Atlas_Diffuse} position={[-0.526, -0.15, -0.151]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell030.geometry} material={materials.Atlas_Diffuse} position={[0.802, -0.057, 0.489]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell031.geometry} material={materials.Atlas_Diffuse} position={[0.267, 0.028, 0.233]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell032.geometry} material={materials.Atlas_Diffuse} position={[-0.985, -1.025, -0.264]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell033.geometry} material={materials.Atlas_Diffuse} position={[-0.266, 0.452, -0.511]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell034.geometry} material={materials.Atlas_Diffuse} position={[0.79, 0.115, 0.328]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell035.geometry} material={materials.Atlas_Diffuse} position={[0.46, 0.625, -0.146]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell037.geometry} material={materials.Atlas_Diffuse} position={[-0.295, -0.372, 0.215]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell038.geometry} material={materials.Atlas_Diffuse} position={[-0.009, -0.169, 0.135]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell039.geometry} material={materials.Atlas_Diffuse} position={[-0.012, 0.268, -0.183]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell040.geometry} material={materials.Atlas_Diffuse} position={[1.013, 0.958, -0.254]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell041.geometry} material={materials.Atlas_Diffuse} position={[0.262, 0.734, -0.362]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell043.geometry} material={materials.Atlas_Diffuse} position={[-0.332, 0.145, -0.123]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell046.geometry} material={materials.Atlas_Diffuse} position={[0.699, 0.374, 0.228]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell047.geometry} material={materials.Atlas_Diffuse} position={[0.004, -0.094, 0.212]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell048.geometry} material={materials.Atlas_Diffuse} position={[0.2, -0.113, 0.259]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell049.geometry} material={materials.Atlas_Diffuse} position={[-0.181, 0.274, -0.294]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell050.geometry} material={materials.Atlas_Diffuse} position={[-0.753, -0.133, -0.422]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell051.geometry} material={materials.Atlas_Diffuse} position={[0.432, -0.402, 0.779]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell052.geometry} material={materials.Atlas_Diffuse} position={[0.245, 0.11, 0.127]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell053.geometry} material={materials.Atlas_Diffuse} position={[0.194, -0.011, 0.146]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell054.geometry} material={materials.Atlas_Diffuse} position={[-0.004, 1.54, -0.39]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell055.geometry} material={materials.Atlas_Diffuse} position={[0.111, 0.19, 0.02]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell057.geometry} material={materials.Atlas_Diffuse} position={[-0.239, -0.251, 0.137]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell058.geometry} material={materials.Atlas_Diffuse} position={[-0.756, -0.075, -0.295]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell059.geometry} material={materials.Atlas_Diffuse} position={[-0.451, -0.458, 0.179]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell060.geometry} material={materials.Atlas_Diffuse} position={[-1.048, -0.961, -0.264]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell061.geometry} material={materials.Atlas_Diffuse} position={[0.727, -0.099, 0.677]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell062.geometry} material={materials.Atlas_Diffuse} position={[0.588, 0.478, -0.108]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell063.geometry} material={materials.Atlas_Diffuse} position={[0.79, 0.187, 0.468]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell064.geometry} material={materials.Atlas_Diffuse} position={[0.43, 0.117, 0.218]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell065.geometry} material={materials.Atlas_Diffuse} position={[0.132, 0.025, 0.077]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell066.geometry} material={materials.Atlas_Diffuse} position={[-0.154, -0.097, 0.134]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell067.geometry} material={materials.Atlas_Diffuse} position={[-0.131, -0.216, 0.112]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell069.geometry} material={materials.Atlas_Diffuse} position={[-0.682, -0.429, 0.009]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell070.geometry} material={materials.Atlas_Diffuse} position={[0.292, 0.302, -0.023]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell071.geometry} material={materials.Atlas_Diffuse} position={[0.581, 0.551, 0.027]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell072.geometry} material={materials.Atlas_Diffuse} position={[0.57, -0.277, 0.728]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell073.geometry} material={materials.Atlas_Diffuse} position={[-0.079, -1.505, -0.382]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell074.geometry} material={materials.Atlas_Diffuse} position={[-0.673, 0.145, -0.43]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell075.geometry} material={materials.Atlas_Diffuse} position={[-1.028, 0.985, -0.254]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell076.geometry} material={materials.Atlas_Diffuse} position={[0.566, -0.115, 0.597]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell077.geometry} material={materials.Atlas_Diffuse} position={[0.333, -0.154, 0.388]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell078.geometry} material={materials.Atlas_Diffuse} position={[1.013, -0.997, -0.254]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell079.geometry} material={materials.Atlas_Diffuse} position={[0.078, 0.107, -0.047]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell080.geometry} material={materials.Atlas_Diffuse} position={[-0.442, -0.006, -0.243]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell081.geometry} material={materials.Atlas_Diffuse} position={[-0.454, -0.117, -0.013]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell082.geometry} material={materials.Atlas_Diffuse} position={[0.104, -0.075, 0.162]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell084.geometry} material={materials.Atlas_Diffuse} position={[-0.225, 0.089, -0.19]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell085.geometry} material={materials.Atlas_Diffuse} position={[0.593, 0.616, -0.238]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell086.geometry} material={materials.Atlas_Diffuse} position={[-0.107, -0.03, -0.017]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell087.geometry} material={materials.Atlas_Diffuse} position={[-0.295, 0.035, -0.151]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell088.geometry} material={materials.Atlas_Diffuse} position={[-0.914, -0.891, -0.264]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell089.geometry} material={materials.Atlas_Diffuse} position={[0.093, 0.732, -0.436]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell090.geometry} material={materials.Atlas_Diffuse} position={[0.448, -0.507, 0.659]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell091.geometry} material={materials.Atlas_Diffuse} position={[-0.264, -0.111, -0.028]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell092.geometry} material={materials.Atlas_Diffuse} position={[-0.524, 0.263, -0.425]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell094.geometry} material={materials.Atlas_Diffuse} position={[-0.003, 0.108, -0.069]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell095.geometry} material={materials.Atlas_Diffuse} position={[0.685, 0.354, 0.077]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell096.geometry} material={materials.Atlas_Diffuse} position={[-0.502, 0.202, -0.553]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell001.geometry} material={materials.Atlas_Diffuse} position={[-0.464, 0.385, -0.526]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell009.geometry} material={materials.Atlas_Diffuse} position={[-0.341, 0.584, -0.595]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell017.geometry} material={materials.Atlas_Diffuse} position={[0.022, 0.168, 0.018]} scale={1.438} />
      <mesh geometry={nodes.Coin_cell036.geometry} material={materials.Atlas_Diffuse} position={[-0.784, -0.577, -0.106]} scale={1.438} />
    </group>
  )
}

useGLTF.preload('/models/coin.glb')
