/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/dil.glb -o src/app/components/canvas/models/Dil.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import useAnimStore from "@/useAnimStore";
import { useExplode } from "../../../../hooks/useExplode";

export function Dil(props) {
  const { nodes, materials } = useGLTF("/models/dil.glb");

  const menu = useAnimStore((state) => state.menu);

  const groupRef = useRef();

  useExplode(groupRef, {
    distance: 50,
    menu: menu,
    Ix: 1.5,
    Iy:-1,
    Iz: -0.5,
    Fx: 1.4,
    Fy: -0.6,
    Fz: -0.6,
  });
  return (
    <group {...props} dispose={null} ref={groupRef}>
      <mesh
        geometry={nodes.Heart_Full_cell.geometry}
        material={materials.Red}
        position={[-0.531, 0.202, -0.097]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell001.geometry}
        material={materials.Red}
        position={[0.218, 1.453, -0.692]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell002.geometry}
        material={materials.Red}
        position={[0.263, -0.441, -0.26]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell003.geometry}
        material={materials.Red}
        position={[0.576, 1.077, -1.092]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell004.geometry}
        material={materials.Red}
        position={[-0.397, 1.329, 0.461]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell005.geometry}
        material={materials.Red}
        position={[-0.664, 0.44, 0.412]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell006.geometry}
        material={materials.Red}
        position={[0.177, 0.664, -1.217]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell007.geometry}
        material={materials.Red}
        position={[0.288, 0.025, -0.275]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell008.geometry}
        material={materials.Red}
        position={[-0.41, 0.648, -0.064]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell009.geometry}
        material={materials.Red}
        position={[-0.381, 0.349, -0.584]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell010.geometry}
        material={materials.Red}
        position={[0.447, 0.501, -0.332]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell011.geometry}
        material={materials.Red}
        position={[0.281, -0.417, 0.066]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell012.geometry}
        material={materials.Red}
        position={[0.253, 0.266, -0.906]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell013.geometry}
        material={materials.Red}
        position={[-0.29, 0.731, -1.094]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell014.geometry}
        material={materials.Red}
        position={[-0.454, 0.797, 1.185]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell015.geometry}
        material={materials.Red}
        position={[-0.033, 0.777, 1.282]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell016.geometry}
        material={materials.Red}
        position={[0.324, 1.112, 0.073]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell017.geometry}
        material={materials.Red}
        position={[-0.393, -0.599, -0.085]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell018.geometry}
        material={materials.Red}
        position={[0.425, 0.438, 0.94]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell019.geometry}
        material={materials.Red}
        position={[-0.391, 1.381, 0.899]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell020.geometry}
        material={materials.Red}
        position={[-0.25, 1.02, -0.056]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell021.geometry}
        material={materials.Red}
        position={[-0.307, 0.376, -1.016]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell022.geometry}
        material={materials.Red}
        position={[-0.261, 1.332, -0.558]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell023.geometry}
        material={materials.Red}
        position={[0.174, -0.452, 0.304]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell024.geometry}
        material={materials.Red}
        position={[0.48, 1.364, -0.462]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell025.geometry}
        material={materials.Red}
        position={[-0.48, 0.01, 0.57]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell026.geometry}
        material={materials.Red}
        position={[0.497, 0.718, 0.135]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell027.geometry}
        material={materials.Red}
        position={[-0.099, -0.042, 0.585]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell028.geometry}
        material={materials.Red}
        position={[-0.614, 0.735, 0.834]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell029.geometry}
        material={materials.Red}
        position={[0.032, -0.649, 0.007]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell030.geometry}
        material={materials.Red}
        position={[-0.577, 1.123, 1.098]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell031.geometry}
        material={materials.Red}
        position={[-0.122, -0.361, -0.283]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell032.geometry}
        material={materials.Red}
        position={[-0.528, 0.261, -0.337]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell033.geometry}
        material={materials.Red}
        position={[0.433, 1.052, 0.545]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell034.geometry}
        material={materials.Red}
        position={[0.343, 0.753, 1.102]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell035.geometry}
        material={materials.Red}
        position={[-0.014, 1.204, 0.326]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell036.geometry}
        material={materials.Red}
        position={[0.64, 0.969, -0.411]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell037.geometry}
        material={materials.Red}
        position={[-0.382, 0.399, 0.973]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell038.geometry}
        material={materials.Red}
        position={[0.041, 1.386, -0.997]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell039.geometry}
        material={materials.Red}
        position={[-0.56, -0.132, -0.089]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell040.geometry}
        material={materials.Red}
        position={[0.418, 0.756, 0.748]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell041.geometry}
        material={materials.Red}
        position={[0.239, 1.361, 0.578]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell042.geometry}
        material={materials.Red}
        position={[-0.586, 0.25, 0.104]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell043.geometry}
        material={materials.Red}
        position={[-0.717, 1.167, 0.729]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell044.geometry}
        material={materials.Red}
        position={[0.141, 0.088, 0.832]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell045.geometry}
        material={materials.Red}
        position={[0.078, 1.236, -0.284]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell046.geometry}
        material={materials.Red}
        position={[-0.18, -0.066, -0.633]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell047.geometry}
        material={materials.Red}
        position={[0.425, 1.148, 0.938]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell048.geometry}
        material={materials.Red}
        position={[-0.044, 1.141, -1.232]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell049.geometry}
        material={materials.Red}
        position={[-0.253, -0.403, 0.189]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell050.geometry}
        material={materials.Red}
        position={[-0.356, 0.771, -0.664]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell051.geometry}
        material={materials.Red}
        position={[0.209, 0.005, 0.272]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell052.geometry}
        material={materials.Red}
        position={[-0.416, 1.156, -0.883]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell053.geometry}
        material={materials.Red}
        position={[0.612, 0.685, -0.954]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell054.geometry}
        material={materials.Red}
        position={[-0.532, 0.922, 0.42]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell055.geometry}
        material={materials.Red}
        position={[0.648, 0.468, -0.718]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell056.geometry}
        material={materials.Red}
        position={[-0.201, 1.164, 1.238]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell057.geometry}
        material={materials.Red}
        position={[0.263, 0.458, 0.516]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell058.geometry}
        material={materials.Red}
        position={[-0.614, 0.42, 0.684]}
      />
      <mesh
        geometry={nodes.Heart_Full_cell059.geometry}
        material={materials.Red}
        position={[0.038, 0.459, 1.042]}
      />
    </group>
  );
}

useGLTF.preload("/models/dil.glb");
