import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/menu/Navbar";
import World from "../components/canvas/World";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="fixed top-0 right-0 w-full h-screen z-40 ">
          <Suspense fallback={null}>
            <World />
          </Suspense>
        </div>
        {children}
      </body>
    </html>
  );
}





